# -*- coding: utf-8 -*-
""".1448

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIIClHvqMtYFqLpA0aV6XldITsz-gvPx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
from wordcloud import WordCloud, STOPWORDS
from collections import Counter

import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/1. users_data.csv')

df.head()

df.tail()

df.sample()

df.describe().T.plot(kind='bar')

df.describe(include = 'all').T

df.columns.to_list()

df.duplicated().sum()

df.isnull().sum()

for col in df:
  sns.histplot(x=col, data=df,kde=True)
  plt.show()